// Bible Chat — Bible Books Data & Sample Verses

import type { BibleBook, BibleVerse } from '../types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { id: 'gen', name: 'Genesis', shortName: 'Gen', testament: 'old', chapters: 50, order: 1 },
  { id: 'exo', name: 'Exodus', shortName: 'Exo', testament: 'old', chapters: 40, order: 2 },
  { id: 'lev', name: 'Leviticus', shortName: 'Lev', testament: 'old', chapters: 27, order: 3 },
  { id: 'num', name: 'Numbers', shortName: 'Num', testament: 'old', chapters: 36, order: 4 },
  { id: 'deu', name: 'Deuteronomy', shortName: 'Deu', testament: 'old', chapters: 34, order: 5 },
  { id: 'jos', name: 'Joshua', shortName: 'Jos', testament: 'old', chapters: 24, order: 6 },
  { id: 'jdg', name: 'Judges', shortName: 'Jdg', testament: 'old', chapters: 21, order: 7 },
  { id: 'rut', name: 'Ruth', shortName: 'Rut', testament: 'old', chapters: 4, order: 8 },
  { id: '1sa', name: '1 Samuel', shortName: '1Sa', testament: 'old', chapters: 31, order: 9 },
  { id: '2sa', name: '2 Samuel', shortName: '2Sa', testament: 'old', chapters: 24, order: 10 },
  { id: '1ki', name: '1 Kings', shortName: '1Ki', testament: 'old', chapters: 22, order: 11 },
  { id: '2ki', name: '2 Kings', shortName: '2Ki', testament: 'old', chapters: 25, order: 12 },
  { id: '1ch', name: '1 Chronicles', shortName: '1Ch', testament: 'old', chapters: 29, order: 13 },
  { id: '2ch', name: '2 Chronicles', shortName: '2Ch', testament: 'old', chapters: 36, order: 14 },
  { id: 'ezr', name: 'Ezra', shortName: 'Ezr', testament: 'old', chapters: 10, order: 15 },
  { id: 'neh', name: 'Nehemiah', shortName: 'Neh', testament: 'old', chapters: 13, order: 16 },
  { id: 'est', name: 'Esther', shortName: 'Est', testament: 'old', chapters: 10, order: 17 },
  { id: 'job', name: 'Job', shortName: 'Job', testament: 'old', chapters: 42, order: 18 },
  { id: 'psa', name: 'Psalms', shortName: 'Psa', testament: 'old', chapters: 150, order: 19 },
  { id: 'pro', name: 'Proverbs', shortName: 'Pro', testament: 'old', chapters: 31, order: 20 },
  { id: 'ecc', name: 'Ecclesiastes', shortName: 'Ecc', testament: 'old', chapters: 12, order: 21 },
  { id: 'sng', name: 'Song of Solomon', shortName: 'SoS', testament: 'old', chapters: 8, order: 22 },
  { id: 'isa', name: 'Isaiah', shortName: 'Isa', testament: 'old', chapters: 66, order: 23 },
  { id: 'jer', name: 'Jeremiah', shortName: 'Jer', testament: 'old', chapters: 52, order: 24 },
  { id: 'lam', name: 'Lamentations', shortName: 'Lam', testament: 'old', chapters: 5, order: 25 },
  { id: 'ezk', name: 'Ezekiel', shortName: 'Ezk', testament: 'old', chapters: 48, order: 26 },
  { id: 'dan', name: 'Daniel', shortName: 'Dan', testament: 'old', chapters: 12, order: 27 },
  { id: 'hos', name: 'Hosea', shortName: 'Hos', testament: 'old', chapters: 14, order: 28 },
  { id: 'jol', name: 'Joel', shortName: 'Jol', testament: 'old', chapters: 3, order: 29 },
  { id: 'amo', name: 'Amos', shortName: 'Amo', testament: 'old', chapters: 9, order: 30 },
  { id: 'oba', name: 'Obadiah', shortName: 'Oba', testament: 'old', chapters: 1, order: 31 },
  { id: 'jon', name: 'Jonah', shortName: 'Jon', testament: 'old', chapters: 4, order: 32 },
  { id: 'mic', name: 'Micah', shortName: 'Mic', testament: 'old', chapters: 7, order: 33 },
  { id: 'nam', name: 'Nahum', shortName: 'Nam', testament: 'old', chapters: 3, order: 34 },
  { id: 'hab', name: 'Habakkuk', shortName: 'Hab', testament: 'old', chapters: 3, order: 35 },
  { id: 'zep', name: 'Zephaniah', shortName: 'Zep', testament: 'old', chapters: 3, order: 36 },
  { id: 'hag', name: 'Haggai', shortName: 'Hag', testament: 'old', chapters: 2, order: 37 },
  { id: 'zec', name: 'Zechariah', shortName: 'Zec', testament: 'old', chapters: 14, order: 38 },
  { id: 'mal', name: 'Malachi', shortName: 'Mal', testament: 'old', chapters: 4, order: 39 },
  // New Testament
  { id: 'mat', name: 'Matthew', shortName: 'Mat', testament: 'new', chapters: 28, order: 40 },
  { id: 'mrk', name: 'Mark', shortName: 'Mrk', testament: 'new', chapters: 16, order: 41 },
  { id: 'luk', name: 'Luke', shortName: 'Luk', testament: 'new', chapters: 24, order: 42 },
  { id: 'jhn', name: 'John', shortName: 'Jhn', testament: 'new', chapters: 21, order: 43 },
  { id: 'act', name: 'Acts', shortName: 'Act', testament: 'new', chapters: 28, order: 44 },
  { id: 'rom', name: 'Romans', shortName: 'Rom', testament: 'new', chapters: 16, order: 45 },
  { id: '1co', name: '1 Corinthians', shortName: '1Co', testament: 'new', chapters: 16, order: 46 },
  { id: '2co', name: '2 Corinthians', shortName: '2Co', testament: 'new', chapters: 13, order: 47 },
  { id: 'gal', name: 'Galatians', shortName: 'Gal', testament: 'new', chapters: 6, order: 48 },
  { id: 'eph', name: 'Ephesians', shortName: 'Eph', testament: 'new', chapters: 6, order: 49 },
  { id: 'php', name: 'Philippians', shortName: 'Php', testament: 'new', chapters: 4, order: 50 },
  { id: 'col', name: 'Colossians', shortName: 'Col', testament: 'new', chapters: 4, order: 51 },
  { id: '1th', name: '1 Thessalonians', shortName: '1Th', testament: 'new', chapters: 5, order: 52 },
  { id: '2th', name: '2 Thessalonians', shortName: '2Th', testament: 'new', chapters: 3, order: 53 },
  { id: '1ti', name: '1 Timothy', shortName: '1Ti', testament: 'new', chapters: 6, order: 54 },
  { id: '2ti', name: '2 Timothy', shortName: '2Ti', testament: 'new', chapters: 4, order: 55 },
  { id: 'tit', name: 'Titus', shortName: 'Tit', testament: 'new', chapters: 3, order: 56 },
  { id: 'phm', name: 'Philemon', shortName: 'Phm', testament: 'new', chapters: 1, order: 57 },
  { id: 'heb', name: 'Hebrews', shortName: 'Heb', testament: 'new', chapters: 13, order: 58 },
  { id: 'jas', name: 'James', shortName: 'Jas', testament: 'new', chapters: 5, order: 59 },
  { id: '1pe', name: '1 Peter', shortName: '1Pe', testament: 'new', chapters: 5, order: 60 },
  { id: '2pe', name: '2 Peter', shortName: '2Pe', testament: 'new', chapters: 3, order: 61 },
  { id: '1jn', name: '1 John', shortName: '1Jn', testament: 'new', chapters: 5, order: 62 },
  { id: '2jn', name: '2 John', shortName: '2Jn', testament: 'new', chapters: 1, order: 63 },
  { id: '3jn', name: '3 John', shortName: '3Jn', testament: 'new', chapters: 1, order: 64 },
  { id: 'jud', name: 'Jude', shortName: 'Jud', testament: 'new', chapters: 1, order: 65 },
  { id: 'rev', name: 'Revelation', shortName: 'Rev', testament: 'new', chapters: 22, order: 66 },
];

// Sample verses for the daily verse feature and demonstrations
export const DAILY_VERSES: BibleVerse[] = [
  { id: 'jer2911', book: 'Jeremiah', chapter: 29, verse: 11, text: 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.', translation: 'NIV' },
  { id: 'php413', book: 'Philippians', chapter: 4, verse: 13, text: 'I can do all things through Christ which strengtheneth me.', translation: 'KJV' },
  { id: 'psa234', book: 'Psalms', chapter: 23, verse: 4, text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', translation: 'NIV' },
  { id: 'rom828', book: 'Romans', chapter: 8, verse: 28, text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.', translation: 'NIV' },
  { id: 'isa4031', book: 'Isaiah', chapter: 40, verse: 31, text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', translation: 'KJV' },
  { id: 'psa461', book: 'Psalms', chapter: 46, verse: 10, text: 'Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.', translation: 'NIV' },
  { id: 'jhn316', book: 'John', chapter: 3, verse: 16, text: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', translation: 'KJV' },
  { id: 'pro356', book: 'Proverbs', chapter: 3, verse: 5, text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', translation: 'KJV' },
  { id: 'mat1128', book: 'Matthew', chapter: 11, verse: 28, text: 'Come to me, all you who are weary and burdened, and I will give you rest.', translation: 'NIV' },
  { id: 'psa1191', book: 'Psalms', chapter: 119, verse: 105, text: 'Thy word is a lamp unto my feet, and a light unto my path.', translation: 'KJV' },
  { id: 'isa4110', book: 'Isaiah', chapter: 41, verse: 10, text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.', translation: 'NIV' },
  { id: 'psa914', book: 'Psalms', chapter: 91, verse: 4, text: 'He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart.', translation: 'NIV' },
  { id: 'jhn1427', book: 'John', chapter: 14, verse: 27, text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.', translation: 'NIV' },
  { id: '2ti17', book: '2 Timothy', chapter: 1, verse: 7, text: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', translation: 'KJV' },
  { id: 'psa483', book: 'Psalms', chapter: 4, verse: 8, text: 'In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety.', translation: 'NIV' },
];

// Sample Psalm 23 for Bible Reader demo
export const PSALM_23: BibleVerse[] = [
  { id: 'psa23-1', book: 'Psalms', chapter: 23, verse: 1, text: 'The LORD is my shepherd; I shall not want.', translation: 'KJV' },
  { id: 'psa23-2', book: 'Psalms', chapter: 23, verse: 2, text: 'He maketh me to lie down in green pastures: he leadeth me beside the still waters.', translation: 'KJV' },
  { id: 'psa23-3', book: 'Psalms', chapter: 23, verse: 3, text: 'He restoreth my soul: he leadeth me in the paths of righteousness for his name\'s sake.', translation: 'KJV' },
  { id: 'psa23-4', book: 'Psalms', chapter: 23, verse: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.', translation: 'KJV' },
  { id: 'psa23-5', book: 'Psalms', chapter: 23, verse: 5, text: 'Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.', translation: 'KJV' },
  { id: 'psa23-6', book: 'Psalms', chapter: 23, verse: 6, text: 'Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.', translation: 'KJV' },
];

// Genesis 1 sample for Bible Reader
export const GENESIS_1: BibleVerse[] = [
  { id: 'gen1-1', book: 'Genesis', chapter: 1, verse: 1, text: 'In the beginning God created the heaven and the earth.', translation: 'KJV' },
  { id: 'gen1-2', book: 'Genesis', chapter: 1, verse: 2, text: 'And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.', translation: 'KJV' },
  { id: 'gen1-3', book: 'Genesis', chapter: 1, verse: 3, text: 'And God said, Let there be light: and there was light.', translation: 'KJV' },
  { id: 'gen1-4', book: 'Genesis', chapter: 1, verse: 4, text: 'And God saw the light, that it was good: and God divided the light from the darkness.', translation: 'KJV' },
  { id: 'gen1-5', book: 'Genesis', chapter: 1, verse: 5, text: 'And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.', translation: 'KJV' },
  { id: 'gen1-6', book: 'Genesis', chapter: 1, verse: 6, text: 'And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.', translation: 'KJV' },
  { id: 'gen1-7', book: 'Genesis', chapter: 1, verse: 7, text: 'And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.', translation: 'KJV' },
  { id: 'gen1-8', book: 'Genesis', chapter: 1, verse: 8, text: 'And God called the firmament Heaven. And the evening and the morning were the second day.', translation: 'KJV' },
  { id: 'gen1-9', book: 'Genesis', chapter: 1, verse: 9, text: 'And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.', translation: 'KJV' },
  { id: 'gen1-10', book: 'Genesis', chapter: 1, verse: 10, text: 'And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.', translation: 'KJV' },
];

export const TRANSLATIONS = [
  { id: 'KJV', name: 'King James Version', year: 1611 },
  { id: 'NIV', name: 'New International Version', year: 1978 },
  { id: 'NKJV', name: 'New King James Version', year: 1982 },
  { id: 'ESV', name: 'English Standard Version', year: 2001 },
  { id: 'NLT', name: 'New Living Translation', year: 1996 },
  { id: 'NASB', name: 'New American Standard Bible', year: 1971 },
  { id: 'NRSV', name: 'New Revised Standard Version', year: 1989 },
  { id: 'AMP', name: 'Amplified Bible', year: 1965 },
  { id: 'WEB', name: 'World English Bible', year: 2000 },
  { id: 'CSB', name: 'Christian Standard Bible', year: 2017 },
  { id: 'MSG', name: 'The Message', year: 2002 },
];
