// Bible Chat — Meditation Sessions & Breathing Exercises Data

import type { MeditationSession, BreathingExercise, MeditationCourse } from '../types';

export const MEDITATION_SESSIONS: MeditationSession[] = [
  {
    id: 'med-peace-1',
    title: 'Be Still & Know',
    description: 'A gentle meditation on Psalm 46:10. Release your anxieties and rest in God\'s presence.',
    category: 'peace',
    duration: 600,
    scriptures: ['Psalm 46:10', 'Psalm 23:2', 'Isaiah 30:15'],
    backgroundSound: 'rain',
    isPremium: false,
  },
  {
    id: 'med-peace-2',
    title: 'Peace That Passes Understanding',
    description: 'Let the peace of Christ guard your heart and mind as you meditate on Philippians 4:6-7.',
    category: 'peace',
    duration: 900,
    scriptures: ['Philippians 4:6-7', 'John 14:27', 'Colossians 3:15'],
    backgroundSound: 'ocean',
    isPremium: false,
  },

  {
    id: 'med-gratitude-1',
    title: 'A Heart of Thanksgiving',
    description: 'Cultivate gratitude through Scripture as you reflect on God\'s blessings in your life.',
    category: 'gratitude',
    duration: 600,
    scriptures: ['Psalm 100:4', '1 Thessalonians 5:18', 'Colossians 3:17'],
    backgroundSound: 'birds',
    isPremium: false,
  },
  {
    id: 'med-forgiveness-1',
    title: 'Letting Go & Forgiving',
    description: 'A meditation on releasing bitterness and embracing God\'s grace for yourself and others.',
    category: 'forgiveness',
    duration: 900,
    scriptures: ['Ephesians 4:31-32', 'Matthew 6:14-15', 'Colossians 3:13'],
    backgroundSound: 'creek',
    isPremium: false,
  },
  {
    id: 'med-strength-1',
    title: 'Strength in Weakness',
    description: 'When you feel depleted, God\'s power is made perfect. Rest in His strength.',
    category: 'strength',
    duration: 600,
    scriptures: ['2 Corinthians 12:9-10', 'Isaiah 40:31', 'Philippians 4:13'],
    backgroundSound: 'forest',
    isPremium: false,
  },
  {
    id: 'med-sleep-1',
    title: 'Peaceful Sleep with Psalm 91',
    description: 'Drift into restful sleep under the shelter of the Most High.',
    category: 'sleep',
    duration: 1200,
    scriptures: ['Psalm 91:1-4', 'Psalm 4:8', 'Proverbs 3:24'],
    backgroundSound: 'rain',
    isPremium: false,
  },

  {
    id: 'med-sleep-2',
    title: 'Good Night Prayer Meditation',
    description: 'End your day surrendering worries to God and receiving His rest.',
    category: 'sleep',
    duration: 900,
    scriptures: ['Matthew 11:28', 'Psalm 127:2', 'Psalm 4:8'],
    backgroundSound: 'whitenoise',
    isPremium: true,
  },
  {
    id: 'med-morning-1',
    title: 'Morning Awakening',
    description: 'Start your day with intention, gratitude, and God\'s presence.',
    category: 'morning',
    duration: 300,
    scriptures: ['Psalm 5:3', 'Lamentations 3:22-23', 'Psalm 143:8'],
    backgroundSound: 'birds',
    isPremium: false,
  },
  {
    id: 'med-healing-1',
    title: 'Healing & Comfort',
    description: 'For times of grief, pain, or illness. Let God\'s healing presence surround you.',
    category: 'healing',
    duration: 900,
    scriptures: ['Psalm 147:3', 'Isaiah 53:5', 'Jeremiah 17:14'],
    backgroundSound: 'ocean',
    isPremium: false,
  },
  {
    id: 'med-identity-1',
    title: 'Who God Says You Are',
    description: 'Meditate on your true identity in Christ. You are loved, chosen, and enough.',
    category: 'identity',
    duration: 600,
    scriptures: ['Ephesians 2:10', '1 Peter 2:9', 'Galatians 2:20'],
    backgroundSound: 'worship',
    isPremium: true,
  },
  {
    id: 'med-surrender-1',
    title: 'Surrendering Control',
    description: 'Release your grip on outcomes and trust God\'s sovereign plan.',
    category: 'surrender',
    duration: 900,
    scriptures: ['Proverbs 3:5-6', 'Psalm 37:5', 'Romans 8:28'],
    backgroundSound: 'creek',
    isPremium: true,
  },
];


export const BREATHING_EXERCISES: BreathingExercise[] = [
  {
    id: 'breath-1',
    name: 'Be Still — Box Breathing',
    description: 'A 4-4-4-4 box breathing pattern paired with Psalm 46:10.',
    pattern: {
      inhale: 4,
      holdIn: 4,
      exhale: 4,
      holdOut: 4,
      cycles: 6,
      inhaleText: 'Be still...',
      holdInText: 'and know...',
      exhaleText: 'that I am God.',
      holdOutText: 'Psalm 46:10',
    },
    scripture: 'Be still, and know that I am God.',
    scriptureReference: 'Psalm 46:10',
    duration: 192,
  },
  {
    id: 'breath-2',
    name: 'Cast Your Anxieties — 4-7-8',
    description: 'The calming 4-7-8 pattern with 1 Peter 5:7.',
    pattern: {
      inhale: 4,
      holdIn: 7,
      exhale: 8,
      holdOut: 0,
      cycles: 5,
      inhaleText: 'Cast all your anxiety...',
      holdInText: 'on Him...',
      exhaleText: 'because He cares for you.',
      holdOutText: '',
    },
    scripture: 'Cast all your anxiety on him because he cares for you.',
    scriptureReference: '1 Peter 5:7',
    duration: 95,
  },
  {
    id: 'breath-3',
    name: 'The Lord is My Shepherd',
    description: 'A gentle breath prayer following Psalm 23.',
    pattern: {
      inhale: 5,
      holdIn: 2,
      exhale: 5,
      holdOut: 2,
      cycles: 7,
      inhaleText: 'The Lord is my shepherd...',
      holdInText: 'I trust You...',
      exhaleText: 'I shall not want.',
      holdOutText: 'Thank You, Lord.',
    },
    scripture: 'The LORD is my shepherd; I shall not want.',
    scriptureReference: 'Psalm 23:1',
    duration: 98,
  },

  {
    id: 'breath-4',
    name: 'Peace I Leave With You',
    description: 'Deep belly breathing with Jesus\' words of peace from John 14:27.',
    pattern: {
      inhale: 6,
      holdIn: 3,
      exhale: 6,
      holdOut: 3,
      cycles: 5,
      inhaleText: 'Peace I leave with you...',
      holdInText: 'My peace I give you...',
      exhaleText: 'Do not be afraid.',
      holdOutText: 'Rest in His peace.',
    },
    scripture: 'Peace I leave with you; my peace I give you.',
    scriptureReference: 'John 14:27',
    duration: 90,
  },
  {
    id: 'breath-5',
    name: 'God Has Not Given Us Fear',
    description: 'Courage-building breathing with 2 Timothy 1:7.',
    pattern: {
      inhale: 4,
      holdIn: 4,
      exhale: 6,
      holdOut: 2,
      cycles: 6,
      inhaleText: 'God has not given us...',
      holdInText: 'a spirit of fear...',
      exhaleText: 'but of power, love, and a sound mind.',
      holdOutText: 'I am safe.',
    },
    scripture: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.',
    scriptureReference: '2 Timothy 1:7',
    duration: 96,
  },
];

export const MEDITATION_COURSES: MeditationCourse[] = [
  {
    id: 'course-peace-7',
    title: '7 Days of Peace',
    description: 'A beginner-friendly journey into Christian meditation, one peaceful day at a time.',
    sessions: MEDITATION_SESSIONS.filter(s => s.category === 'peace').slice(0, 2),
    totalDays: 7,
    category: 'peace',
    isPremium: false,
  },
  {
    id: 'course-sleep-7',
    title: '7 Nights of Rest',
    description: 'Fall asleep in God\'s arms with nightly meditations on His protection and love.',
    sessions: MEDITATION_SESSIONS.filter(s => s.category === 'sleep'),
    totalDays: 7,
    category: 'sleep',
    isPremium: true,
  },
  {
    id: 'course-identity-14',
    title: '14 Days: Who God Says You Are',
    description: 'Discover and internalize your identity in Christ through daily meditation.',
    sessions: MEDITATION_SESSIONS.filter(s => s.category === 'identity'),
    totalDays: 14,
    category: 'identity',
    isPremium: true,
  },
];
